const PRODUCTS = [
  {
    id: "m1",
    name: "Vanilla Matcha Latte",
    category: "matcha",
    desc: "Creamy matcha with vanilla sweetness.",
    price: 4.9,
    popular: 10,
    options: ["Oat milk", "Almond milk", "Regular milk"],
  },
  {
    id: "m2",
    name: "Strawberry Matcha",
    category: "matcha",
    desc: "Matcha + strawberry foam vibes.",
    price: 5.5,
    popular: 9,
    options: ["Oat milk", "Coconut milk", "Regular milk"],
  },
  {
    id: "m3",
    name: "Iced Matcha Lemonade",
    category: "matcha",
    desc: "Fresh, bright, and super iced.",
    price: 4.4,
    popular: 7,
    options: ["Less sweet", "Normal", "Extra sweet"],
  },
  {
    id: "c1",
    name: "Iced Vanilla Latte",
    category: "coffee",
    desc: "Classic iced latte with vanilla.",
    price: 4.7,
    popular: 10,
    options: ["Oat milk", "Regular milk", "Extra espresso shot"],
  },
  {
    id: "c2",
    name: "Caramel Cold Brew",
    category: "coffee",
    desc: "Cold brew + caramel cream.",
    price: 5.2,
    popular: 8,
    options: ["Normal ice", "Less ice", "Extra ice"],
  },
  {
    id: "c3",
    name: "Mocha Iced Coffee",
    category: "coffee",
    desc: "Chocolate + coffee = perfect.",
    price: 4.8,
    popular: 6,
    options: ["Whipped cream", "No cream", "Extra cocoa"],
  },
];
